name: '⭐️ 功能需求'
description: '提出需求或建议'
title: '[Feature] '
labels: ['⭐️ Feature Request']
assignees: 
  - samwafgo
body:
  - type: input
    attributes:
      label: '产品版本'
      description: 产品版本。
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: '版本类型'
      options:
        - label: '社区版' 
    validations:
      required: true 
  - type: textarea
    attributes:
      label: '⭐️ 需求描述'
      description: |
        请添加一个清晰且简洁的问题描述，阐述你希望通过这个功能需求解决的问题。<br/>
        针对不清晰的描述信息将不予处理。
    validations:
      required: true 

  - type: textarea
    attributes:
      label: '补充信息'
      description: 在这里添加关于问题的任何其他背景信息。
